### ISSUE TITLE
Edycja droidów

### ISSUE THREAD

**Issue by patryksliwinski** [patryksliwinski/Star-Wars-warehouse#3]
Dodanie opcji edycji partii
Pole edytowalne

- ilość droidów
- nazwę
- wersję oprogramowania droida
- umiejętności specjalne

**Comment by patryksliwinski** [comment]
Zablokowane przez #2

**Comment by patryksliwinski** [comment]
Odblokowane

**Comment by ZuzannaDul** [comment]
zrobione
